### ISSUE TITLE
send silently handle all errors

### ISSUE THREAD

**Issue by bakwc** [bashkirtsevich-llc/aioudp#3]
I got an error: `TypeError: a bytes-like object is required, not 'str' when writing to a file in Python3`
Spend a lot of time debuging, cause you silently handle all errors:
```
        except Exception as e:
            fut.set_result(0)
            self._socket_error(e)
```
BTW, awesome library, thank you for sharing!

**Comment by bashkirtsevich** [comment]
Fixed in [this commit](https://github.com/bashkirtsevich-llc/aioudp/commit/c1b551c12859258c5799722ec8b2e4197c0d5c0d)
New version 0.0.7
